spring:
 jpa:
  show-sql: true
  hibernate.ddl-auto: create
  database-platform: org.hibernate.dialect.MySQL8Dialect

 datasource:
  url: jdbc:mysql://localhost:3306/person?createDatabaseIfNotExist=true
  username: root
  password: root
  driver-class-name: com.mysql.cj.jdbc.Driver

server:
 port: 8081
